# Generated by Django 5.1.5 on 2025-02-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อรถ')),
                ('brand', models.CharField(max_length=100, verbose_name='ยี่ห้อ')),
                ('seats', models.PositiveIntegerField(verbose_name='จำนวนที่นั่ง')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา/วัน')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='รูปภาพ')),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van')], max_length=50)),
                ('model', models.CharField(max_length=255, verbose_name='รุ่น')),
                ('year', models.PositiveIntegerField(verbose_name='ปีที่ผลิต')),
                ('available', models.BooleanField(default=True, verbose_name='พร้อมให้เช่า')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'รถยนต์',
                'verbose_name_plural': 'รถยนต์ทั้งหมด',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='รูปโปรไฟล์')),
                ('is_admin', models.BooleanField(default=False, verbose_name='เป็นแอดมิน')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้ทั้งหมด',
            },
        ),
    ]
