# Generated by Django 5.1.5 on 2025-02-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ส่วนลด (%)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='ไม่มีข้อมูล', verbose_name='รายละเอียด'),
        ),
    ]
