# Generated by Django 5.1.5 on 2025-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_discount_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
