# Generated by Django 5.1.5 on 2025-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_doors_alter_car_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=4, verbose_name='จำนวนประตู'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5, verbose_name='จำนวนที่นั่ง'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van')], max_length=50, verbose_name='ประเภทรถ'),
        ),
    ]
