# Generated by Django 5.1.5 on 2025-02-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(verbose_name='ละติจูด'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อสถานที่'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(verbose_name='วันที่รับรถ')),
                ('dropoff_date', models.DateTimeField(verbose_name='วันที่คืนรถ')),
                ('full_name', models.CharField(max_length=100, verbose_name='ชื่อผู้จอง')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car', verbose_name='รถที่จอง')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff', to='myapp.location', verbose_name='สถานที่คืนรถ')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='myapp.location', verbose_name='สถานที่รับรถ')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจองทั้งหมด',
                'ordering': ['-pickup_date'],
            },
        ),
    ]
